version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.2'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=vulcan
      - MONGODB_DATABASE=vulcan
      - MONGODB_PASSWORD=vulcan
  
  redis:
    image: bitnami/redis:5.0
    restart: on-failure
    environment:
      - REDIS_PASSWORD=vulcan
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
  redis_data: {}
