version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.2'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_USERNAME=vulcan
      - MONGODB_DATABASE=vulcan
      - MONGODB_PASSWORD=vulcan
  
  redis:
    image: redis:5.0-alpine
    restart: on-failure
    ports:
      - 6379:6379

volumes:
  postgres_data: {}
  mongodb_data:
    driver: local
